export const GET_TODOLIST='getTodolist'
export const ADD_LIST='addList'
export const DELETE_LIST='deleteList'
export const CHANGE_INPUT='changeInput'
export const CHANGE_HEADERKEY='change_headerkey'
export const CHANGE_HEADERSHOW='change_headershow'
export const CHANGE_SIDEKEY='change_sidekey'
export const GETOWNERLIST='getOwnerlist'
export const CHANGE_LOADINGSHOW='changeloadingshow'
export const CHNAGE_SEARCHINPUT='change_searchinput'
export const GET_FILTERSEARCH='getfiltersearch'
export const CHANGE_PAGEKEY='change_pagekey'
export const GET_CREATESTATUS='get_createstatus'

